DataBiosphere/terra-policy-service

README.md, service/build.gradle
The projectName in build.gradle is needed to label the scan properly in SonarCloud.
The badge in README.md is recommended but not required.
=> SonarCloud projectName and README badge

buildSrc/src/main/groovy/bio.terra.policy.java-common-conventions.gradle, service/src/main/java/bio/terra/policy/db/PaoDao.java, service/src/main/resources/policydb/changelog.xml, service/src/main/resources/policydb/changesets/20220811_attribute_set_index.yaml, testharness/src/main/java/bio/terra/policy/app/Main.java
Two changes in this PR:
1. Add retry to the database transactions. This makes sure we don't just fail on a serialization error, but instead rerun the transaction.
2. Add an index to set_id in the attribute_set table. This should make serialization errors less likely. The table has no primary key, so there was no index. That meant every attribute set operation - like delete - would scan the entire table. With the index, there should be no row overlaps on the table operations.
=> [PF-1899] Add retry to database transactions

service/IMPLEMENTATION_NOTES.md, service/build.gradle, service/src/main/java/bio/terra/policy/common/model/PolicyInput.java, service/src/main/java/bio/terra/policy/common/model/PolicyInputs.java, service/src/main/java/bio/terra/policy/common/model/PolicyName.java, service/src/main/java/bio/terra/policy/db/DbAdditionalData.java, service/src/main/java/bio/terra/policy/db/DbAttribute.java, service/src/main/java/bio/terra/policy/db/DbPao.java, service/src/main/java/bio/terra/policy/db/DbSerDes.java, service/src/main/java/bio/terra/policy/db/PaoDao.java, service/src/main/java/bio/terra/policy/service/pao/PaoService.java, service/src/main/java/bio/terra/policy/service/pao/graph/Walker.java, service/src/main/java/bio/terra/policy/service/pao/graph/model/GraphNode.java, service/src/main/java/bio/terra/policy/service/pao/graph/model/PolicyConflict.java, service/src/main/java/bio/terra/policy/service/pao/model/Pao.java, service/src/main/java/bio/terra/policy/service/pao/model/PaoUpdateMode.java, service/src/main/java/bio/terra/policy/service/policy/PolicyBase.java, service/src/main/java/bio/terra/policy/service/policy/PolicyCombiner.java, service/src/main/java/bio/terra/policy/service/policy/PolicyGroupConstraint.java, service/src/main/java/bio/terra/policy/service/policy/model/ChangeDescription.java, service/src/main/java/bio/terra/policy/service/policy/model/LinkSourceResult.java, service/src/main/resources/policydb/changelog.xml, service/src/main/resources/policydb/changesets/20220812_pao_features.yaml, testharness/src/test/java/bio/terra/policy/service/pao/PaoServiceTest.java, testharness/src/test/java/bio/terra/policy/service/policy/CombinerTest.java
This PR is an omnibus of changes driven by working through how propagating changes and conflicts would work. I'm putting this code in now so Mike can work on his TPS tickets in parallel with my getting the update path tested and debugged.
Some notable changes:
- Added a predecessor pointer to support clone 
- Renamed `children` to `sources`
- Removed the `in_conflict` boolean from the PAO
- Added a list of conflicting object ids to the policy attribute
- changed additional data from being a Map to a Multimap, so we have a better way of supporting things like group-constraint
- added DbAdditionalData to put Multimap into a serializable format for database storage, and back again
- Added non-transactional methods to support graph walk and update as one big transactions.
- Added graph model …
=> [PF-1634] Rename child/parent to source/dependent; add update processing

service/src/main/java/bio/terra/policy/common/model/PolicyInput.java, service/src/main/java/bio/terra/policy/common/model/PolicyInputs.java, service/src/main/java/bio/terra/policy/db/PaoDao.java, service/src/main/java/bio/terra/policy/service/pao/PaoService.java, service/src/main/java/bio/terra/policy/service/pao/graph/Walker.java, service/src/main/java/bio/terra/policy/service/pao/graph/model/AttributeEvaluator.java, service/src/main/java/bio/terra/policy/service/pao/graph/model/GraphAttribute.java, service/src/main/java/bio/terra/policy/service/pao/graph/model/GraphAttributeConflict.java, service/src/main/java/bio/terra/policy/service/pao/graph/model/GraphAttributeSet.java, service/src/main/java/bio/terra/policy/service/pao/graph/model/GraphNode.java, service/src/main/java/bio/terra/policy/service/pao/graph/model/PolicyConflict.java, service/src/main/java/bio/terra/policy/service/pao/model/Pao.java, testharness/src/test/java/bio/terra/policy/service/pao/PaoUpdateTest.java
I rewrote the attribute evaluation to give a consistent result on conflicts and to propagate conflicts through the dependents rather than stopping at the first one.
The code is very close to the algorithm outlined in [Policy Conflict Implementation Notes](https://docs.google.com/document/d/1GUJA_DTPdvigFh9JEcnbd668EBiil6nBQwYLxKK9MXg/edit?resourcekey=0-vOR9fDJIaEvAYquvWHLBeA#heading=h.qet38xi4p78c)
I plan to integrate those notes into the implementation notes markdown as a separate task.
I added classes in the `graph` package to support the walk. Now rather than trying to operate directly on the Pao object, it operates on these graph objects.
@yuhuyoyo I didn't tag you for a review, but feel free to add yourself if you'd like to look at the new code.
=> [PF-1927] revamp attribute evaluation and add tests

service/src/main/java/bio/terra/policy/db/PaoDao.java, testharness/src/test/java/bio/terra/policy/service/pao/PaoServiceTest.java
This came up when trying to clone a workspace PAO when the origin workspace didn't have a PAO. The problem was the query was expecting one result and threw a different exception when there were no matches. This fix lets us throw the internal exception as expected.
=> PF-1966: fix getPao throws EmptyResultDataAccessException when no matching PAO is found

service/src/main/java/bio/terra/policy/db/DbPao.java, service/src/main/java/bio/terra/policy/db/PaoDao.java, service/src/main/java/bio/terra/policy/service/pao/PaoService.java, service/src/main/java/bio/terra/policy/service/pao/graph/DeleteWalker.java, service/src/main/java/bio/terra/policy/service/pao/graph/model/DeleteGraphNode.java, service/src/main/java/bio/terra/policy/service/pao/model/Pao.java, service/src/main/resources/policydb/changelog.xml, service/src/main/resources/policydb/changesets/20220830_pao_deleted.yaml, testharness/src/test/java/bio/terra/policy/service/pao/PaoDeleteTest.java
Added logic for deleting PAOs. When calling delete on a PAO:
If the target is not referenced as a policy source, then we remove the PAO from the graph. Also, recursively inspect its sources to see if they now have no dependents. If not, they can be removed if they were previously flagged as deleted.
If the target was referenced as a source, then flag it as deleted but leave it in the graph.
=> PF-1951: Implementation for PAO delete

service/src/main/java/bio/terra/policy/common/exception/IllegalCycleException.java, service/src/main/java/bio/terra/policy/db/PaoDao.java, service/src/main/java/bio/terra/policy/service/pao/PaoService.java, testharness/src/test/java/bio/terra/policy/service/pao/PaoUpdateTest.java
We need to ensure the graph of policy objects is a DAG - it cannot have cycles.
This PR adds a cycle test to the link. I thought this would be a bit of code, but I was able to use recursion in Postgres. It was simple to make a query that returned all descendants. Then I just need to test if the link source is on that list.
Piggy-backed onto an existing test that builds a hierarchy of PAOs.
@yuhuyoyo I thought you might want to look at the SQL for this. Maybe it would make the cycle check for folders simpler?
=> [PF-2034] Add check for cycles to linkSource

service/src/main/java/bio/terra/policy/service/pao/PaoService.java, service/src/main/java/bio/terra/policy/service/policy/model/PolicyUpdateResult.java, testharness/src/test/java/bio/terra/policy/service/pao/PaoReplaceTest.java, testharness/src/test/java/bio/terra/policy/service/pao/PaoUpdateTest.java
The update method we had to support users has lists of policies to add and remove.
That is inconvenient to use as part of `undo()` processing when a flight has made changes to the policy graph.
The PR adds a `replace` method that provides the policy attributes to be replaced wholesale. The implementation shares a lot with `update`, so I factored out the common part.
=> [PF-2019] Add replace method and tests

service/src/main/java/bio/terra/policy/db/PaoDao.java, service/src/main/java/bio/terra/policy/service/pao/PaoService.java
Small PR to switch over to the simple `@WriteTransaction` and `@ReadTransaction` marks.
We couldn't use these inside WSM, because we used a different transaction manager. In our own service, we can.
=> [PF-2071] Use the simple transaction marks

.github/workflows/tag-publish.yml
TPS is failing to deploy in Broad deployment because of a mismatch between where we are putting the docker image and where the helm file is reading it.
=> [PF-2168] Switch GCR project; remove unused env

service/src/main/java/bio/terra/policy/service/region/RegionService.java, service/src/main/java/bio/terra/policy/service/region/model/Datacenter.java, service/src/main/java/bio/terra/policy/service/region/model/Region.java, service/src/main/resources/static/datacenters.yml, service/src/main/resources/static/regions.yml, service/src/test/java/bio/terra/policy/service/region/RegionServiceTest.java
Regions and datacenters are added as .yml files. Eventually we may want to persist these into the db.
This includes the methods for determining if a datacenter is inside of a region, which would enable what's needed for PF-2240.
=> PF-2239 Add region ontology

common/openapi.yml, service/src/main/java/bio/terra/policy/app/controller/TpsApiController.java, service/src/main/java/bio/terra/policy/service/region/RegionService.java, service/src/test/java/bio/terra/policy/service/region/RegionServiceTest.java
This is for the DRY_RUN scenario where we aren't storing a PAO and so we can't use it to look up policies and regions. In this case, all we have is the policy inputs but we can use those to check for region constraints and build the list of valid data centers from it.
=> PF-2303: API to list-valid regions given PolicyInputs

service/src/main/resources/policy-application.yml
Broad infrastructure is configured to use 8080. I had set the port to 8085. Revert that.
=> [PF-2344] Change port to 8080

service/src/main/resources/static/regions.yml, service/src/test/java/bio/terra/policy/service/policy/PolicyRegionConstraintTest.java, service/src/test/java/bio/terra/policy/service/region/RegionServiceTest.java
Fills in the single datacenter regions rather than leaving them dangling on a higher-level region.
=> PF-2328 fill out the region ontology with single datacenter regions

common/openapi.yml, service/src/main/java/bio/terra/policy/app/controller/ConversionUtils.java, service/src/main/java/bio/terra/policy/app/controller/TpsApiController.java, service/src/main/java/bio/terra/policy/service/region/RegionService.java, service/src/test/java/bio/terra/policy/service/region/RegionServiceTest.java
Adds 2 APIs -
GET /regions which will let you query by region name to find subregions.
GET /regions/datacenters which gets a flattened list of data centers available in a region and subregions.
=> PF-2292: API for exploring the region ontology

.github/workflows/tag-publish.yml
Following in the footsteps of https://github.com/DataBiosphere/terra-workspace-manager/pull/953, use ['the new way'](https://docs.google.com/document/d/1lkUkN2KOpHKWufaqw_RIE7EN3vN4G2xMnYBU83gi8VA/edit#) to deploy new TPS versions to dev.
=> [DDO-2570] Report new TPS versions directly to DevOps and deploy directly to dev

service/src/main/java/bio/terra/policy/service/region/RegionService.java, service/src/test/java/bio/terra/policy/service/region/RegionServiceTest.java
Code wasn't checking for null data centers, so there was an error when the ontology was called for a region which contains no data centers. That included the global/default region.
=> Bug fix for calling region endpoint with no regionName

service/src/main/java/bio/terra/policy/common/exception/DirectConflictException.java
run into this exception. i think it should throw 409 given it's called a conflict?
=> [no ticket] throw 409 for conflict

.github/workflows/build-and-test.yml, .github/workflows/linter-tests.yml
Only run PR checks when the PR targets primary/default branch
currently, all PRs (irrespective of the branch they target) automatically trigger PR checks. This is unnecessary and may cause the checks to be queued up on GitHub runner.
ref - 
- https://github.com/DataBiosphere/terra-workspace-manager/pull/1061
- https://broadworkbench.atlassian.net/browse/PF-2478
=> [PF-2478] Only run checks when PR targets default branch

service/src/main/java/bio/terra/policy/service/pao/PaoService.java, service/src/main/java/bio/terra/policy/service/policy/PolicyGroupConstraint.java, service/src/main/java/bio/terra/policy/service/policy/PolicyMutator.java, service/src/main/java/bio/terra/policy/service/policy/PolicyRegionConstraint.java, service/src/main/java/bio/terra/policy/service/policy/PolicyUnknown.java, service/src/test/java/bio/terra/policy/service/policy/PolicyGroupConstraintTest.java, service/src/test/java/bio/terra/policy/service/policy/PolicyRegionConstraintTest.java
For group constraints, we have the requirement where we should not allow a Workspace with no group constraint to combine with a Data Collection that has a different group constraint. The default behavior allowed this.
=> PF-2498: disallow combining group constraint when destination is empty

client/src/main/resources/swaggercodegen/libraries/jersey2/ApiClient.mustache
Per [ApacheConnector docs](https://eclipse-ee4j.github.io/jersey.github.io/apidocs/2.29.1/jersey/org/glassfish/jersey/apache/connector/ApacheClientProperties.html#CONNECTION_MANAGER), we shouldn't be using the default connection manager in a multi-threaded environment. From local testing, this seems to fix the `NoHttpResponseException` errors WSM is hitting.
=> [PF-2531] Use PoolingHttpClientConnectionManager instead of default

service/src/main/java/bio/terra/policy/service/pao/PaoService.java, service/src/test/java/bio/terra/policy/service/pao/PaoUpdateTest.java, service/src/test/java/bio/terra/policy/service/policy/PolicyGroupConstraintTest.java, service/src/test/java/bio/terra/policy/service/policy/PolicyRegionConstraintTest.java, service/src/test/java/bio/terra/policy/service/policy/PolicyTestUtils.java, service/src/test/java/bio/terra/policy/testutils/PaoTestUtil.java
We were working from a blank slate and then calculating removes and adds. This change will existing set and remove/replace inputs into it as necessary.
=> PF-2509: update PAO overwrites existing attributes

client/src/main/resources/swaggercodegen/libraries/jersey2/ApiClient.mustache
The `NoHttpResponseException`s we keep seeing indicate the TPS server (or the proxy in front of it, anyway) is closing connections that the client thinks are still open. These aren't timeouts, as the requests fail almost immediately.
This fix is a bit of a bandaid, as it doesn't address whatever is causing the TPS server to close connections (I believe that's somewhere in the Broad's proxy or ingress setup, but I can't find where. It's also different than Verily, where we don't see this issue). Instead, this makes the client more aggressive about validating connections before using them. This is enough to catch all the stale connections I've seen so far, which gets rid of all `NoHttpResponseException`s.
Tested locally and in https://github.com/DataBiosphere/terra-workspace-manager/pull/110 …
=> [PF-2531] Set default client connection validation time lower

client/src/main/resources/swaggercodegen/libraries/jersey2/ApiClient.mustache
First, increase the max number of connections from 2 -> 20. This is a small improvement when running multiple test threads locally, so it probably also helps with live servers. This also matches the default of the previous `JdkConnectorProvider`.
Second, validate inactive connections after 1ms, which is the closest we can get to always validating connections before use, which matches older client behavior. This eliminates the `NoHttpResponseException` errors we keep seeing due to Terra servers unexpectedly (to the client, anyway) closing connections.
Tested in WSM (https://github.com/DataBiosphere/terra-workspace-manager/actions/runs/4348772074/jobs/7599148331),
=> [PF-2531] In default client library, always validate connection before use

service/src/main/java/bio/terra/policy/common/model/PolicyInputs.java, service/src/main/java/bio/terra/policy/service/pao/PaoService.java, service/src/main/java/bio/terra/policy/service/policy/PolicyGroupConstraint.java, service/src/test/java/bio/terra/policy/controller/TpsBasicControllerTest.java, service/src/test/java/bio/terra/policy/service/pao/PaoUpdateTest.java, service/src/test/java/bio/terra/policy/service/policy/PolicyGroupConstraintTest.java, service/src/test/java/bio/terra/policy/testutils/PaoTestUtil.java
We can't update auth domains in SAM during milestone 1. So we shouldn't allow updating the group constraints on a PAO either.
I have a review out for updating the test in WSM for this. That should be completed before we merge this change.
=> PF-2563: Disallow updating of group constraints

service/src/main/java/bio/terra/policy/common/model/Constants.java, service/src/main/java/bio/terra/policy/service/pao/PaoService.java, service/src/main/java/bio/terra/policy/service/policy/PolicyMutator.java, service/src/main/java/bio/terra/policy/service/policy/PolicyUnknown.java, service/src/test/java/bio/terra/policy/service/pao/PaoDeleteTest.java, service/src/test/java/bio/terra/policy/service/pao/PaoMergeTest.java, service/src/test/java/bio/terra/policy/service/pao/PaoReplaceTest.java, service/src/test/java/bio/terra/policy/service/pao/PaoServiceTest.java, service/src/test/java/bio/terra/policy/testutils/PaoTestUtil.java
We had validation while updating & merging policies, but not during initial create or replace. We should validate those too.
=> PF-2610: Validate policyInputs during PAO Create/Replace

client/src/main/resources/swaggercodegen/libraries/jersey2/ApiClient.mustache
This configures the TPS client not to re-use connections older than 45s, rather than the default behavior of assuming connections are always reusable until they fail. This aligns better with Terra's backend services, which generally drop unused connections after ~60s. This change fixes the "Connection Reset" errors WSM tests have been seeing in calls to TPS.
I chose 45s somewhat arbitrarily as close enough to 60s without race conditions being a concern. If this becomes a significant performance issue, we can revisit this time.
Tested in https://github.com/DataBiosphere/terra-workspace-manager/pull/1138 and upstream in Verily's deployment
=> [PF-2580] Set max connection TTL on TPS client

common/openapi.yml, service/src/main/java/bio/terra/policy/app/controller/ConversionUtils.java, service/src/main/java/bio/terra/policy/app/controller/TpsApiController.java, service/src/main/java/bio/terra/policy/db/DbPao.java, service/src/main/java/bio/terra/policy/db/PaoDao.java, service/src/main/java/bio/terra/policy/service/pao/PaoService.java, service/src/main/java/bio/terra/policy/service/pao/model/Pao.java, service/src/main/resources/policydb/changelog.xml, service/src/main/resources/policydb/changesets/20230405_dates.yaml, service/src/test/java/bio/terra/policy/controller/TpsBasicControllerTest.java, service/src/test/java/bio/terra/policy/controller/TpsExplainControllerTest.java
Add created and lastUpdated to
- OpenAPI
- database schema
- DAO
- PAO model
- Conversion of PAO to OpenAPI
Added checks in two tests to validate update changes.
=> [PF-2234] Add created and lastUpdated to policy objects

common/openapi.yml
Missed the Swagger API spec in [my last PR](https://github.com/DataBiosphere/terra-policy-service/pull/61).
=> PF-2685: Add AWS platform to Swagger spec.

buildSrc/build.gradle, service/build.gradle
snakeyaml 1.33 was still getting pulled in, moving the dependency declaration to the buildSrc gradle file looks like it will fix it
=> [ID-630] upgrade snakeyaml in buildsrc

buildSrc/build.gradle, service/build.gradle
terra-common-libs has been overriding our snakeYAML version, trying to make sure that it's correctly upgraded and the vulnerability actually goes away in the security scan
=> [ID-631] upgrade snakeyaml again AGAIN

service/src/main/resources/static/locations.yml
Currently, the names of all individual GCP regions in the location ontology are prefixed with gcp-. However, the US and EU multiregions are not. We should fix these, both for consistency and because these prefixes are currently the most reliable way for API callers to determine the cloud platform of a particular region. These regions already have the `cloudPlatform` field set to `gcp`.
According to a Github search of DataBiosphere and BroadInstitute orgs, these locations are both currently unused.
=> [PF-2903] Add gcp prefix to EU and US multiregions

service/build.gradle
This pulls in the latest version of TCL, with the only change being an update to the `grpc-xds` library (https://github.com/DataBiosphere/terra-common-lib/pull/114)
=> [ID-683] Update TCL version

service/src/main/resources/static/locations.yml
Shows up in the same file ~50 lines above. Causes the region to be returned twice in the API call.
=> remove duplciated asia-southeast2

service/src/main/resources/static/locations.yml
Verily's UI currently reads the region from the `name` field of the region ontology for regions prefixed with `gcp`, as `cloudPlatform` isn't available from the API.  We should fix this API, but in the mean time the multi-region locations should match GCP's values.
=> [PF-2907] Match GCP multiregion names

buildSrc/build.gradle, buildSrc/src/main/groovy/bio.terra.policy.java-common-conventions.gradle, service/build.gradle
Verily security has started using a different dependency analysis tool which flagged a handful of vulnerabilities. I'd like to update dependencies to fix issues raised by both Verily's tool and Sourceclear.
I verified the dependency versions are changed by generating lockfiles locally, though it looks like this service generally isn't using them anymore so I didn't include them in this PR.
=> [PF-2972] Update dependencies with known vulnerabilities

service/src/main/resources/policy-application.yml
TPS is not exposing metrics in a way that is scrape-able by Prometheus for usage in Grafana. 
* Switches to a prometheus scrape-able format, with the metrics available at /actuator/prometheus
* Adds percentile histograms for request latencies. I've taken a stab at the bucket min/max of 10ms/10s. Given that TPS makes no calls to external services this seems like a reasonable place to start.  [See this reference PR](https://github.com/DataBiosphere/terra-drs-hub/pull/90)
=> [WOR-1411] Enable prometheus scrapable endpoints

service/build.gradle
```
The following version in use was found to contain a vulnerability: 1.4.11
Upgrading to a non-vulnerable version of this library will fix this finding. The fixed version of this library is: 1.4.12
```
The newest version is 1.4.14 so I upgraded to that.
=> ID-947 Upgrade logback to fix vulnerability.

buildSrc/src/main/groovy/bio.terra.policy.java-common-conventions.gradle, service/build.gradle
I accidentally only upgraded it for the migration last time wooops. This time I double checked with a dependency scan.
=> ID-947 Upgrade logback to fix vulnerability. Take 2.

service/src/main/java/bio/terra/policy/common/model/Constants.java, service/src/main/java/bio/terra/policy/service/policy/KnownPolicy.java, service/src/main/java/bio/terra/policy/service/policy/PolicyDataTrackingConstraint.java, service/src/test/java/bio/terra/policy/service/policy/PolicyDataTrackingConstraintTest.java, service/src/test/java/bio/terra/policy/testutils/PaoTestUtil.java
Ticket: [WOR-1596](https://broadworkbench.atlassian.net/browse/WOR-1596)
* Add new known policy type to TPS for data tracking which contains the type of the data as `additionalData`. This policy behaves similarly to the group constraint policy in how it is combined and validated. The main difference is that TPS will allow the policy to be removed which is the same behavior as the `protected-data` policy. WSM will likely still disallow policy removal
[WOR-1596]: https://broadworkbench.atlassian.net/browse/WOR-1596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WOR-1596] Add data-tracking policy

service/publishing.gradle
Ticket: https://broadworkbench.atlassian.net/browse/CORE-45
**Description:**
This PR upgrades the base image from jre:17-distroless to jre:17-12-distroless to fix a security vulnerability. Service compatibility has been checked, and tests have been run to ensure everything works as expected.
**Infosec Discussion:**
Reference: [Message from David Bernick in #dsp-engineering.](https://broadinstitute.slack.com/archives/C0DSD41QT/p1728328182615109)
=> [CORE-45] Upgrade Base Image to jre:17-12-distroless for Security Fix

.github/workflows/tag-publish.yml
Jira: [\<Link to Jira ticket\>](https://broadworkbench.atlassian.net/browse/CORE-246)
What:
Upgrades all actions/cache to v4
Why:
The cache backend service has been rewritten from the ground up for improved performance and reliability. [actions/cache](https://github.com/actions/cache) now integrates with the new cache service (v2) APIs.
The new service will gradually roll out as of February 1st, 2025. The legacy service will also be sunset on the same date. Changes in these release are fully backward compatible.
More info here: https://github.com/marketplace/actions/cache
How:
This makes all our repos use the same version of actions/cache.
=> CORE-246 Upgrading to cache v4

common/openapi.yml, service/src/main/java/bio/terra/policy/service/pao/model/PaoComponent.java
Ticket: [CORE-437](https://broadworkbench.atlassian.net/browse/CORE-437)
* Add Rawls as a supported component since it will now be calling TPS directly
[CORE-437]: https://broadworkbench.atlassian.net/browse/CORE-437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CORE-437] Add Rawls as a component

buildSrc/src/main/groovy/bio.terra.policy.java-common-conventions.gradle
Jira ticket: https://broadworkbench.atlassian.net/browse/DDO-4107
**Summary of changes**
Updated the artifact source for this service to read artifacts from Google Artifact Registry instead of JFrog.
**What**
Modified the config to pull artifacts from GAR. No publishing changes were made.
**Why**
This is part of Phase 2 of the artifact migration effort to deprecated JFrog and consolidate artifacts in GAR.
**Testing these changes**
Relied on passing CI checks and tests. Artifact reading-related issues are expected to surface as pipeline failures. For example these jobs [here](https://github.com/DataBiosphere/terra-scientific-pipelines-service/actions/runs/15309876591/job/43071753325?pr=222) and [here](https://github.com/DataBiosphere/leonardo/actions/runs/15324072477/job/43114134405?pr=4858 …
=> DDO-4131 read from google artifact registry

.github/workflows/tag-publish.yml
https://github.com/DataBiosphere/terra-policy-service/pull/110 added a `permissions` block to `tag-publish.yml`.  Usually, in order to publish to GAR, this `permissions` block consists of 
```
contents: 'read'
id-token: 'write'
```
However, the publishing job [failed](https://github.com/DataBiosphere/terra-policy-service/actions/runs/16272961038/job/45944996842).  In testing the PR, when this step failed, I thought it was because it was not a "real" publishing, which has been the case in other repos, but when it failed on merge I looked closer.  I *think* what is happening here is that the `contents` permission had previously been `write` and I've overwritten it; looking at the last [successful job](https://github.com/DataBiosphere/terra-policy-service/actions/runs/15418981735/job/43388697 …
=> [CORE-593] Don't set contents permissions

service/src/main/java/bio/terra/policy/db/PaoDao.java
for troubleshooting CORE-648.
This PR tweaks the javadoc for `PaoDao`.
The PR's main purpose is to test client publishing after merge to see if we continue to run into the same errors we see in https://github.com/DataBiosphere/terra-policy-service/actions/runs/16761362156/job/47512890822.
=> CORE-648: proper links in PaoDao javadoc

.github/dependabot.yml
Tweaks to the Dependabot config:
* target branch should be `main`, not `dev`
* add GAR `libs-release-standard` as a repository
=> CORE-657: fix Dependabot target-branch; add GAR repo

.github/dependabot.yml
Follow-on to #123: actually use the `broad-artifactory` private registry in Dependabot updates.
=> CORE-657: add broad-artifactory registry for Dependabot
